language: cpp

compiler:
  - gcc
  - clang
  
cache: ccache

sudo: required
dist: trusty

addons:
    packages:
        - libbz2-dev

script:
    - pushd src
    - make -j2
    - ./ardb-test
    - storage_engine=leveldb make -j2
    - ./ardb-test
    - storage_engine=lmdb make -j2
    - ./ardb-test
    - storage_engine=wiredtiger make -j2
    - ./ardb-test
    - popd

os:
  - linux
