language: cpp

compiler:
  - gcc
  - clang
  
cache: ccache

sudo: required
dist: trusty

addons:
    packages:
        - libbz2-dev
        
        
env:
  matrix:
    - storage_engine=leveldb
    - storage_engine=lmdb
    - storage_engine=wiredtiger
    - storage_engine=''

script:
    - pushd src
    - make -j2
    - ./ardb-test
    - popd

os:
  - linux
