language: cpp

compiler:
  - gcc
  - clang
  
cache: ccache

sudo: required
dist: trusty

addons:
    packages:
        - libbz2-dev
        
        
env:
  matrix:
    - storage_engine=leveldb
    - storage_engine=lmdb
    - storage_engine=wiredtiger

script:
    - pushd src
    - make -j2
    - ./ardb-test
    - popd
matrix:
  include:
    - compiler: gcc
      env:
    - compiler: clang
      env:
os:
  - linux
